services:
  postgres:
    image: postgres:16
    container_name: geography-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: